"""adds pet_count to Cat model

Revision ID: e8fd64bcaf78
Revises: d9b7ac86cb54
Create Date: 2025-12-15 20:12:29.760580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8fd64bcaf78'
down_revision = 'd9b7ac86cb54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pet_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cat', schema=None) as batch_op:
        batch_op.drop_column('pet_count')

    # ### end Alembic commands ###
